disabled_rules:
  - trailing_comma
  - multiple_closures_with_trailing_closure

opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - convenience_type
  - empty_collection_literal
  - empty_count
  - empty_string
  - explicit_init
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicit_return
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - operator_usage_whitespace
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - strict_fileprivate
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

analyzer_rules:
  - explicit_self
  - unused_declaration
  - unused_import

line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true

nesting:
  type_level:
    warning: 2
  statement_level:
    warning: 5

type_name:
  min_length: 3
  max_length: 50

identifier_name:
  min_length: 2
  max_length: 50
  excluded:
    - id
    - up
    - url
    - sdk

function_parameter_count:
  warning: 8
  error: 10

file_length:
  warning: 500
  error: 1000

type_body_length:
  warning:

only_rules:
  - closing_brace
  - closure_spacing
  - colon
  - comma
  - computed_accessors_order
  - empty_enum_arguments
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - mark
  - operator_whitespace
  - redundant_string_enum_value
  - redundant_void_return
  - return_arrow_whitespace
  - trailing_newline
  - trailing_semicolon
  - trailing_whitespace
  - void_return
  - custom_rules