disabled_rules:
  - trailing_comma
  - multiple_closures_with_trailing_closure
  - redundant_sendable
  - nesting
  - identifier_name

opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - convenience_type
  - empty_collection_literal
  - empty_count
  - empty_string
  - explicit_init
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicit_return
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - operator_usage_whitespace
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

line_length:
  warning: 150
  error: 200
  ignores_comments: true
  ignores_urls: true

function_body_length:
  warning: 60
  error: 100

file_length:
  warning: 500
  error: 1000

type_body_length:
  warning: 300
  error: 500

identifier_name:
  min_length: 2
  max_length: 50
  excluded:
    - id
    - up
    - url
    - sdk
    - n

cyclomatic_complexity:
  warning: 12
  error: 15

included:
  - Sources

excluded:
  - Tests
  - Examples

analyzer_rules:
  - explicit_self
  - unused_declaration
  - unused_import