name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: macos-14
    strategy:
      matrix:
        xcode: ['16.0']
        config: ['debug']

    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode ${{ matrix.xcode }}
      run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      
    - name: Build and Test
      run: swift test
      
  swiftlint:
    name: SwiftLint
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Run SwiftLint
      uses: norio-nomura/action-swiftlint@3.2.1
      with:
        args: --strict
        
  docs:
    name: Documentation
    runs-on: macos-14
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Documentation
      run: |
        swift package --allow-writing-to-directory ./docs \
          generate-documentation --target GroqSwift \
          --disable-indexing \
          --transform-for-static-hosting \
          --hosting-base-path groq_swift \
          --output-path ./docs
          
    - name: Upload Documentation
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./docs
